### ISSUE TITLE
Refactor PParty UI into a BOS Widget ♻️

### ISSUE THREAD

**Issue by doulos819** [MarmaJFoundation/pixelparty-website#8]
### Pain
Without a BOS implementation, pixelparty.marmaj.org is difficult to access for most of the NEAR community.

### What code could be improved?
https://github.com/MarmaJFoundation/pixelparty-website

### Tasks
- [ ] Update README for this repo
- [ ] Create a widget for PixelParty
- [ ] Add some basic functionality to view on chain data from the game

### More Information
This task should be done in phases. An MVP version should simple have some buttons and some on chain data, and a final version should provide all smart contract functionality + big fixes in the BOS UI.

Example of MJG widget: https://near.social/#/shemar268abel.near/widget/MJG-Widget

**Comment by Dark-St-r** [comment]
I have been working on getting the UI to be functional on the BOS, but after a few different tries I have failed to do so satisfactorily. Provided is the link to what I have accomplished so far, [here](https://near.social/#/shemar268abel.near/widget/PixelParty)...

My blockers are the restricted nature of iframes on the BOS, and my lack of understanding of smart contracts.
